version: '3.3'
services:
    mycroft:
        volumes:
            - 'mycroft_data:/root/.mycroft/'
            - '${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native'
            - '~/.config/pulse/cookie:/root/.config/pulse/cookie'
        depends_on:
          - gateway
        devices:
            - /dev/snd
        environment:
            - 'PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native'
        networks:
            - default
        container_name: mycroft
        image: mycroftai/docker-mycroft


    gateway:
        environment:
            - TZ=Europe/Berlin
        volumes:
            - 'webthings_data:/home/node/.mozilla-iot'
        networks:
            - default
        ports:
            - '8080:8080'
        container_name: webthings
        image: 'mozillaiot/gateway:0.11.0'
        
volumes:
  mycroft_data:
  webthings_data:
  
networks:
  default:
